name=ruler_lib
version=1.0.0
author=219 Design
maintainer=219 Design <mwong@219design.com>
sentence=sample control of buttons and neopixels on ME218 Ruler PCB 
paragraph=This library allows an Arduino board to control buttons and neopixels on ME218 Ruler PCB.
category=input, output
url=https://github.com/219-design/me218
architectures=*
